### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by neerajaJoshy** [AustinWise/Mcp2515Can#1]
Hello AustinWise

Can you please tell me how I can use this Mcp2515Can files to connect the PiCAN2 board with Raspberry Pi 3 running windows IoT? I opened this project in Visual studio but I am not able to run or debug it. Can you please tell me the steps to be followed to get this working? Thanx a lot. In deperate need:) 
Regards
Neeraja

**Comment by AustinWise** [comment]
Unfortunately this is a work in progress, so it does not current work =(
